### ISSUE TITLE
question of configuration

### ISSUE THREAD

**Issue by fmotnaldo** [alex-leonhardt/sensu-grid#14]
Hi,

I want to configure sensu-grid but I don't know the way to configure the service start up on centos 7. I tried to do it by hand and this is the result and the log.

 [root@ardc02sensu01 start-scripts]# /usr/bin/gunicorn -n sensu-grid --user sensu-grid --group sensu-grid --chdir /opt/sensu-grid --reload --workers 3 --bind 0.0.0.0:5000 --log-file /var/log/sensu-grid.log--log-level info --access-logfile /var/log/sensu-grid.log --error-logfile /var/log/sensu-grid.log
[root@ardc02sensu01 start-scripts]# cat /var/log/sensu-grid.log
[2018-02-23 15:38:23 +0000] [23516] [INFO] Starting gunicorn 19.7.1
[2018-02-23 15:38:23 +0000] [23516] [INFO] Listening at: http://0.0.0.0:5000 (23516)
[2018-02-23 15:38:23 +0000] [23516] [INFO] Using worker: sync
[2018-02-23 15:38:23 +0000] [23532] [INFO] Booting worker with pid: 23532
[2018-02-23 15:38:23 +0000] [23532] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ImportError: No module named info
[2018-02-23 15:38:23 +0000] [23532] [INFO] Worker exiting (pid: 23532)
[2018-02-23 15:38:23 +0000] [23516] [INFO] Shutting down: Master
[2018-02-23 15:38:23 +0000] [23516] [INFO] Reason: Worker failed to boot.
[root@ardc02sensu01 start-scripts]#

**Comment by alex-leonhardt** [comment]
hi, could you let me know what version / commit sha (?) you're working with ? 

the latest version (that comes with centos7 unit script) should no longer even need `gunicorn` 

also the output of these would be useful:

- `pip --freeze`
- `uname -r`
- linux distribution you're using

in case it's a bug I need the above to try to replicate it ...

Thanks
alex

**Comment by fmotnaldo** [comment]
Hi ALex,

Thankd for your repply. This is the output of the commands.

[root@ardc02sensu01 ~]# pip --freeze

Usage:
  pip <command> [options]

no such option: --freeze
[root@ardc02sensu01 ~]# uname -r
3.10.0-693.5.2.el7.x86_64
[root@ardc02sensu01 ~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@ardc02sensu01 ~]#

Maybe I am starting the service in a different way. I included the
sensugrid.conf here.

[root@ardc02sensu01 system]# ls -ltr
total 20
-rw-r--r--. 1 root  root   208 Oct 10 14:48 sensu-server.service
-rw-r--r--. 1 root  root   208 Oct 10 14:48 sensu-client.service
-rw-r--r--. 1 sensu sensu  202 Oct 10 14:48 sensu-api.service
drwxr-xr-x. 2 root  root    44 Nov 17 09:32 system-update.target.wants
drwxr-xr-x. 2 root  root    32 Nov 17 09:32 getty.target.wants
drwxr-xr-x. 2 root  root    87 Nov 17 09:32 default.target.wants
drwxr-xr-x. 2 root  root    29 Nov 17 09:32 sockets.target.wants
lrwxrwxrwx. 1 root  root    57 Nov 17 09:33
dbus-org.freedesktop.nm-dispatcher.service ->
/usr/lib/systemd/system/NetworkManager-dispatcher.service
lrwxrwxrwx. 1 root  root    46 Nov 17 09:33
dbus-org.freedesktop.NetworkManager.service ->
/usr/lib/systemd/system/NetworkManager.service
drwxr-xr-x. 2 root  root    89 Nov 17 09:33 sysinit.target.wants
lrwxrwxrwx. 1 root  root    37 Nov 17 09:36 default.target ->
/lib/systemd/system/multi-user.target
drwxr-xr-x. 2 root  root    24 Nov 17 10:05 redis.service.d
drwxr-xr-x. 2 root  root    24 Nov 17 10:05 redis-sentinel.service.d
drwxr-xr-x. 2 root  root    25 Nov 17 10:06 rabbitmq-server.service.d
drwxr-xr-x. 2 root  root    31 Nov 21 12:47 basic.target.wants
drwxr-xr-x. 2 root  root  4096 Feb 23 14:18 multi-user.target.wants
-rw-r--r--. 1 root  root   756 Feb 23 15:25 sensu-grid.conf
[root@ardc02sensu01 system]#

**Comment by alex-leonhardt** [comment]
apologies, the first command should've been without the `--` ... could you re run: `pip freeze` and send me that output ? 

also, what "version" of sensu-grid are you using? could you pull the latest version (current master) and use the unit file that comes with it? it should not need gunicorn anymore ..

**Comment by alex-leonhardt** [comment]
please don't send the sensu-grid.conf as it may contain secrets ... (api password) ... please sanitise it (remove passwords, some environmental specifics that you feel should not be public) before attaching

**Comment by fmotnaldo** [comment]
Hi Alex,

When I checked the log for /var/log/sensu-grid.log

[root@ardc02sensu01 sensu-grid]# tail -f /var/log/sensu-grid.log
2018-03-05 15:43:25,371 - griddata - DEBUG - Retrieving filters for datacenter: dev
2018-03-05 15:43:25,377 - griddata - ERROR - Got exception while filtering on clients: 403 Client Error: Forbidden for url: http://x.x.x.x:4567/clients
2018-03-05 15:43:25,377 - griddata - ERROR - no reponse
2018-03-05 15:43:25,377 - griddata - ERROR - No response data
2018-03-05 15:43:25,377 - griddata - DEBUG - Filter Retrieval for datacenter dev complete
2018-03-05 15:43:27,691 - griddata - DEBUG - Retrieving filters for datacenter: dev
2018-03-05 15:43:27,697 - griddata - ERROR - Got exception while filtering on clients: 403 Client Error: Forbidden for url: http://x.x.x.x:4567/clients
2018-03-05 15:43:27,697 - griddata - ERROR - no reponse
2018-03-05 15:43:27,697 - griddata - ERROR - No response data
